# Generated by Django 4.2.17 on 2025-01-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size', models.DecimalField(decimal_places=0, max_digits=8)),
                ('description', models.TextField()),
                ('age_limited', models.BooleanField(default=False)),
                ('DecimalField', models.DecimalField(decimal_places=2, max_digits=6)),
                ('BooleanField', models.BooleanField()),
                ('buyer', models.ManyToManyField(related_name='Buyers', to='task1.buyer')),
            ],
        ),
    ]
