# Generated by Django 4.2.17 on 2025-01-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='BooleanField',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='DecimalField',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
