# Generated by Django 4.2.17 on 2025-01-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_news_date_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
